package com.howtogrow.backend.api;

public enum ErrorCode {
  OK,
  UNAUTHORIZED,
  FORBIDDEN_RESOURCE,
  SUBSCRIPTION_REQUIRED,
  FREE_TRIAL_ALREADY_USED,
  DAILY_ASSESSMENT_ALREADY_SUBMITTED,
  DAILY_ASSESSMENT_INCOMPLETE,
  QUESTION_POOL_EXHAUSTED,
  AI_SUMMARY_ALREADY_GENERATED,
  WECHAT_PAY_VERIFY_FAILED,
  WECHAT_PAY_AMOUNT_MISMATCH,
  ORDER_ALREADY_PAID,
  RATE_LIMITED,
  INVALID_REQUEST,
  NOT_FOUND,
  INTERNAL_ERROR
}
